version: '3.3'
services:
  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'berbauser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'berbapass54321'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'berbapass54321'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  flask:
    build: ./flask_web
    restart: always
    environment:
      FLASK_APP: 'app'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5001:5000'
    expose:
      # Opens port 3306 on the container
      - '5001'
# Names our volume
volumes:
  my-db:
